### ISSUE TITLE
Column Lane Terminology Mixup

### ISSUE THREAD

**Issue by Kalaschnik** [lourenci/react-kanban#192]
Hey,
I’m comparing different React-Javascript-based Kanban boards. I noticed that your data model uses the term "lane" to actually describe a column. I noticed the same wrong terminology in a similar project (i.e., react-trello), where I reported that confusing mix up a year ago:
https://github.com/rcdexta/react-trello/issues/126

Out of curiosity, why do you chose that naming scheme?

**Comment by lourenci** [comment]
Hi, @Kalaschnik.

I think you are right. The lane term used here can mix up with the kanban's "right" terminology. I'll manage that for the `v1` release, this will be a good break change.

For your curiosity, this project was inspired heavily by `rcdexta/react-trello` lib, most because I was using it in a private project. The `lane` name came from there.
