### ISSUE TITLE
Remove card

### ISSUE THREAD

**Issue by VipPhilstar** [lourenci/react-kanban#313]
The documentation says that onCardRemove accepts parameters (board, column, card), but in reality only card is transmitted

**Comment by iIdiomatic** [comment]
yes true - noticed same, also parameters are different when using controlled and uncontrolled board

**Comment by lourenci** [comment]
Sorry about that. I'll open an issue to tidy up the documentation.

In a controlled board: it just receives the removed card because you have all the board in your hand, it does not make sense to pass all the board through the callback.

In an uncontrolled board: it receives the modified board, the modified column and the removed card.
