### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Judahh** [lourenci/react-kanban#432]
# When I import the package (in next.js with typescript):
```
import Board, { moveCard } from '@lourenci/react-kanban';
import '@lourenci/react-kanban/dist/styles.css';
```

# I get:
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.

# Source
```
@lourenci/react-kanban (1:0) @ eval

> 1 | module.exports = require("@lourenci/react-kanban");
```

**Comment by samuellaycock** [comment]
This is because NextJS will render on the server first, where `window` is not defined. You can use `process.browser` to conditionally render the `Board` component only on the browser. 

We use `next/dynamic` (https://nextjs.org/docs/advanced-features/dynamic-import) to lazy load our `Board` component in, you can pass that an `ssr: false` flag to skip the server render and also give it a placeholder component to render while it's downloading to the browser.
